### ISSUE TITLE
Dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by geek80** [alvarobartt/covid-daily#1]
Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/5SJ3LP

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by alvarobartt** [comment]
Hi @geek80! Thank you for including it! Sure, I will help you as much as I can, just tell me how and I will do it!

**Comment by geek80** [comment]
Thanks for the reply. You can register in Dataverse and update the metadata for the dataset.

**Comment by geek80** [comment]
Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the Dataset creator permissions to your dataset. Then please add relevant metadata - description and keywords to your dataset.
