### ISSUE TITLE
Can't access the data for different countries

### ISSUE THREAD

**Issue by assemzh** [alvarobartt/covid-daily#2]
When I try to run the code given in the example documentation it doesn't work. It gives data for china, but not for other countries. Can you help me with this, please?

**Comment by alvarobartt** [comment]
Hi @assemzh, there was an error while parsing the HighchartsJS data, but it has already been fixed, so you should be able to install the new version and retrieve data from any country.

```
pip install covid_daily --upgrade
```

__Thank you! Remember to star the repo if you found it useful and follow me at GitHub so as to get notified of all the updates!__
